### ISSUE TITLE
Consider replacing Makefile with standard Node.js rollup

### ISSUE THREAD

**Issue by f1yn** [stasm/innerself#1]
I love what you've managed to do with the Makefile, but right now I am attempting to include a small external library into the root `index.js`, and the current Rollup CLI implementation is making this somewhat difficult. I admit being new to Rollup in general, but as far as I can tell I am unable to use resolve plugins while the Make is CLI based.

This means that I am unable to `import` files into the root `index.js` while also using the make-file. An alternative could be to have a separate Make instance for a library, that bundles the mini sanitation lib with the actual `index.js`. But in my own opinion, that seems a little heavy.

I think this is an awesome project, and I wanna contribute to it if I can. If you'd like I could do my own build implementation and submit a PR when it's ready.

**Comment by f1yn** [comment]
I'm going to continue to work using the `Make` implementation.

**Comment by stasm** [comment]
Thanks for bringing this up. I went for `Makefile` because I'm used to it, but I think using npm's `scripts` would be just as good. At the point where a more advanced Rollup configuration is needed via `rollup.config.js`, `make` becomes just a command runner. `npm run` should be sufficient for this.

I would also like to point out that I don't think any build step is necessary for the library itself. The idea behind putting all source files in the root of the repo and the package is that users can freely pick which parts they need with deep imports: `from "innerself/logger"` is a good example of this.

So this issue should really only apply to the build pipeline of `example01`. Let's reopen it. If you feel like writing it, I would take a PR replacing `example01/Makefile` with `scripts.start` in `example01/package.json` which uses rollup to build, watch, serve and reload (`rollup-plugin-serve` and `rollup-plugin-livereload` can help).

**Comment by f1yn** [comment]
I'm planning on removing the new Makefile, and instead reverting back to the current style of having the `innerself`,  `logger`, and now additionally a `safe` or `clean` file inside of the root directory.

So, if the user wants to use the HTML safe version, they could do:
```javascript
import html from innerself/safe
```

I will be adding a better interface as well, since you've already described to me that you'd like for there to be a way to custom define elements. I will no longer be making changes the `index.js`, but will be focusing on an external file.

**Comment by stasm** [comment]
> since you've already described to me that you'd like for there to be a way to custom define elements.

What I meant is that I would like to allow developers to use all of HTML5 elements by default.

**Comment by f1yn** [comment]
That was just an error my my end. I was in the process of adding a more vigorous checker, but then you informed me you already added your own minimalist one. The one I was adding worked based on whitelisting, so any elements that were allowed (at least by default) would have to be defined in that array.

**Comment by f1yn** [comment]
I'll see about replacing the Make with npm scripts this evening.

**Comment by f1yn** [comment]
I've switched to inline npm scripts in pull: https://github.com/stasm/innerself/pull/3

**Comment by stasm** [comment]
#3 has been merged, thank you!
